/** \file
 *  This C source file was generated by $ANTLR version 3.5.1
 *
 *     -  From the grammar source file : C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g
 *     -                            On : 2014-09-07 01:25:17
 *     -                 for the lexer : ModernLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ModernLexer.h"
/* ----------------------------------------- */


/** String literals used by ModernLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x66, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x69, 0x6E, 0x74,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x63, 0x68, 0x61, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x76, 0x6F, 0x69, 0x64,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pModernLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pModernLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pModernLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pModernLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__30    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mT__31    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mT__32    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mT__33    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mT__34    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mT__35    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mT__36    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mNeverUsedRule    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mFOR    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mINT_TYPE    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mCHAR_TYPE    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mVOID_TYPE    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mID    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mINT    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mEQ    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mEQEQ    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mOPLT    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mPLUS    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pModernLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pModernLexer ctx);
static void	ModernLexerFree(pModernLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
ModernLexerFree  (pModernLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
ModernLexerReset (pModernLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called ModernLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pModernLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pModernLexer ModernLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return ModernLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called ModernLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pModernLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pModernLexer ModernLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pModernLexer ctx; // Context structure we will build and return

    ctx = (pModernLexer) ANTLR3_CALLOC(1, sizeof(ModernLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ModernLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our ModernLexer interface
     */
    ctx->mT__30	= mT__30;
    ctx->mT__31	= mT__31;
    ctx->mT__32	= mT__32;
    ctx->mT__33	= mT__33;
    ctx->mT__34	= mT__34;
    ctx->mT__35	= mT__35;
    ctx->mT__36	= mT__36;
    ctx->mNeverUsedRule	= mNeverUsedRule;
    ctx->mFOR	= mFOR;
    ctx->mINT_TYPE	= mINT_TYPE;
    ctx->mCHAR_TYPE	= mCHAR_TYPE;
    ctx->mVOID_TYPE	= mVOID_TYPE;
    ctx->mID	= mID;
    ctx->mINT	= mINT;
    ctx->mEQ	= mEQ;
    ctx->mEQEQ	= mEQEQ;
    ctx->mOPLT	= mOPLT;
    ctx->mPLUS	= mPLUS;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= ModernLexerFree;
    ctx->reset          = ModernLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:7:7: ( '(' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:7:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 8:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__31
 *
 * Looks to match the characters the constitute the token T__31
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__31(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__31;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:8:7: ( ')' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:8:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__31Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__31Ex; /* Prevent compiler warnings */
    ruleT__31Ex: ;

}
// $ANTLR end T__31

//   Comes from: 9:7: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__32
 *
 * Looks to match the characters the constitute the token T__32
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__32(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__32;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:9:7: ( '*' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:9:9: '*'
    {
        MATCHC('*');
        if  (HASEXCEPTION())
        {
            goto ruleT__32Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__32Ex; /* Prevent compiler warnings */
    ruleT__32Ex: ;

}
// $ANTLR end T__32

//   Comes from: 10:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__33
 *
 * Looks to match the characters the constitute the token T__33
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__33(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__33;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:10:7: ( ',' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:10:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleT__33Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__33Ex; /* Prevent compiler warnings */
    ruleT__33Ex: ;

}
// $ANTLR end T__33

//   Comes from: 11:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__34
 *
 * Looks to match the characters the constitute the token T__34
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__34(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__34;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:11:7: ( ';' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:11:9: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleT__34Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__34Ex; /* Prevent compiler warnings */
    ruleT__34Ex: ;

}
// $ANTLR end T__34

//   Comes from: 12:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__35
 *
 * Looks to match the characters the constitute the token T__35
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__35(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__35;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:12:7: ( '{' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:12:9: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleT__35Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__35Ex; /* Prevent compiler warnings */
    ruleT__35Ex: ;

}
// $ANTLR end T__35

//   Comes from: 13:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__36
 *
 * Looks to match the characters the constitute the token T__36
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__36(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__36;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:13:7: ( '}' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:13:9: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleT__36Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__36Ex; /* Prevent compiler warnings */
    ruleT__36Ex: ;

}
// $ANTLR end T__36

//   Comes from: 126:14: ()
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NeverUsedRule
 *
 * Looks to match the characters the constitute the token NeverUsedRule
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNeverUsedRule(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NeverUsedRule;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:126:14: ()
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:126:32: 
    {
    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNeverUsedRuleEx; /* Prevent compiler warnings */
    ruleNeverUsedRuleEx: ;

}
// $ANTLR end NeverUsedRule

//   Comes from: 128:5: ( 'for' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FOR
 *
 * Looks to match the characters the constitute the token FOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFOR(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = FOR;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:128:5: ( 'for' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:128:7: 'for'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleFOREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleFOREx; /* Prevent compiler warnings */
    ruleFOREx: ;

}
// $ANTLR end FOR

//   Comes from: 129:10: ( 'int' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT_TYPE
 *
 * Looks to match the characters the constitute the token INT_TYPE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT_TYPE(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT_TYPE;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:129:10: ( 'int' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:129:12: 'int'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleINT_TYPEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINT_TYPEEx; /* Prevent compiler warnings */
    ruleINT_TYPEEx: ;

}
// $ANTLR end INT_TYPE

//   Comes from: 130:10: ( 'char' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHAR_TYPE
 *
 * Looks to match the characters the constitute the token CHAR_TYPE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHAR_TYPE(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHAR_TYPE;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:130:10: ( 'char' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:130:12: 'char'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleCHAR_TYPEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCHAR_TYPEEx; /* Prevent compiler warnings */
    ruleCHAR_TYPEEx: ;

}
// $ANTLR end CHAR_TYPE

//   Comes from: 131:10: ( 'void' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start VOID_TYPE
 *
 * Looks to match the characters the constitute the token VOID_TYPE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mVOID_TYPE(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = VOID_TYPE;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:131:10: ( 'void' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:131:12: 'void'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleVOID_TYPEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleVOID_TYPEEx; /* Prevent compiler warnings */
    ruleVOID_TYPEEx: ;

}
// $ANTLR end VOID_TYPE

//   Comes from: 133:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:133:5: ( ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )* )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:133:9: ( 'a' .. 'z' | 'A' .. 'Z' | '_' ) ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*
    {
        if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleIDEx;
        }


        // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:133:33: ( 'a' .. 'z' | 'A' .. 'Z' | '0' .. '9' | '_' )*

        for (;;)
        {
            int alt1=2;
            switch ( LA(1) )
            {
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt1=1;
            	}
                break;

            }

            switch (alt1)
            {
        	case 1:
        	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:
        	    {
        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleIDEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 136:5: ( ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:136:5: ( ( '0' .. '9' )+ )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:136:7: ( '0' .. '9' )+
    {
        // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:136:7: ( '0' .. '9' )+
        {
            int cnt2=0;

            for (;;)
            {
                int alt2=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt2=1;
        		}
        	    break;

        	}

        	switch (alt2)
        	{
        	    case 1:
        	        // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt2 >= 1 )
        		{
        		    goto loop2;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt2++;
            }
            loop2: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 139:6: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQ
 *
 * Looks to match the characters the constitute the token EQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQ(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQ;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:139:6: ( '=' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:139:8: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleEQEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEQEx; /* Prevent compiler warnings */
    ruleEQEx: ;

}
// $ANTLR end EQ

//   Comes from: 140:6: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EQEQ
 *
 * Looks to match the characters the constitute the token EQEQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEQEQ(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = EQEQ;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:140:6: ( '==' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:140:8: '=='
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleEQEQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleEQEQEx; /* Prevent compiler warnings */
    ruleEQEQEx: ;

}
// $ANTLR end EQEQ

//   Comes from: 141:8: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPLT
 *
 * Looks to match the characters the constitute the token OPLT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPLT(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPLT;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:141:8: ( '<' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:141:10: '<'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleOPLTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPLTEx; /* Prevent compiler warnings */
    ruleOPLTEx: ;

}
// $ANTLR end OPLT

//   Comes from: 142:6: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PLUS
 *
 * Looks to match the characters the constitute the token PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPLUS(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PLUS;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:142:6: ( '+' )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:142:8: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto rulePLUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePLUSEx; /* Prevent compiler warnings */
    rulePLUSEx: ;

}
// $ANTLR end PLUS

//   Comes from: 144:5: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pModernLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:144:5: ( ( ' ' | '\\t' | '\\r' | '\\n' )+ )
    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:144:9: ( ' ' | '\\t' | '\\r' | '\\n' )+
    {
        // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:144:9: ( ' ' | '\\t' | '\\r' | '\\n' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case '\n':
        	case '\r':
        	case ' ':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:
        	        {
        	            if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || LA(1) == '\r' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

        {
             LEXSTATE->channel=HIDDEN; 
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pModernLexer ctx)
{
    {
        //  C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:8: ( T__30 | T__31 | T__32 | T__33 | T__34 | T__35 | T__36 | NeverUsedRule | FOR | INT_TYPE | CHAR_TYPE | VOID_TYPE | ID | INT | EQ | EQEQ | OPLT | PLUS | WS )

        ANTLR3_UINT32 alt4;

        alt4=19;

        switch ( LA(1) )
        {
        case '(':
        	{
        		alt4=1;
        	}
            break;
        case ')':
        	{
        		alt4=2;
        	}
            break;
        case '*':
        	{
        		alt4=3;
        	}
            break;
        case ',':
        	{
        		alt4=4;
        	}
            break;
        case ';':
        	{
        		alt4=5;
        	}
            break;
        case '{':
        	{
        		alt4=6;
        	}
            break;
        case '}':
        	{
        		alt4=7;
        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt4=13;
        							}
        						    break;

        						default:
        						    alt4=9;
        						}

        					}
        				    break;

        				default:
        				    alt4=13;
        				}

        			}
        		    break;

        		default:
        		    alt4=13;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'n':
        			{
        				switch ( LA(3) )
        				{
        				case 't':
        					{
        						switch ( LA(4) )
        						{
        						case '0':
        						case '1':
        						case '2':
        						case '3':
        						case '4':
        						case '5':
        						case '6':
        						case '7':
        						case '8':
        						case '9':
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case '_':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt4=13;
        							}
        						    break;

        						default:
        						    alt4=10;
        						}

        					}
        				    break;

        				default:
        				    alt4=13;
        				}

        			}
        		    break;

        		default:
        		    alt4=13;
        		}

        	}
            break;
        case 'c':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'a':
        					{
        						switch ( LA(4) )
        						{
        						case 'r':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt4=13;
        									}
        								    break;

        								default:
        								    alt4=11;
        								}

        							}
        						    break;

        						default:
        						    alt4=13;
        						}

        					}
        				    break;

        				default:
        				    alt4=13;
        				}

        			}
        		    break;

        		default:
        		    alt4=13;
        		}

        	}
            break;
        case 'v':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'd':
        							{
        								switch ( LA(5) )
        								{
        								case '0':
        								case '1':
        								case '2':
        								case '3':
        								case '4':
        								case '5':
        								case '6':
        								case '7':
        								case '8':
        								case '9':
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case '_':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt4=13;
        									}
        								    break;

        								default:
        								    alt4=12;
        								}

        							}
        						    break;

        						default:
        						    alt4=13;
        						}

        					}
        				    break;

        				default:
        				    alt4=13;
        				}

        			}
        		    break;

        		default:
        		    alt4=13;
        		}

        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'd':
        case 'e':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'w':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt4=13;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt4=14;
        	}
            break;
        case '=':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt4=16;
        			}
        		    break;

        		default:
        		    alt4=15;
        		}

        	}
            break;
        case '<':
        	{
        		alt4=17;
        	}
            break;
        case '+':
        	{
        		alt4=18;
        	}
            break;
        case '\t':
        case '\n':
        case '\r':
        case ' ':
        	{
        		alt4=19;
        	}
            break;

        default:
            alt4=8;
        }

        switch (alt4)
        {
    	case 1:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:10: T__30
    	    {
    	        /* 1:10: T__30 */
    	        mT__30(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:16: T__31
    	    {
    	        /* 1:16: T__31 */
    	        mT__31(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:22: T__32
    	    {
    	        /* 1:22: T__32 */
    	        mT__32(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:28: T__33
    	    {
    	        /* 1:28: T__33 */
    	        mT__33(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:34: T__34
    	    {
    	        /* 1:34: T__34 */
    	        mT__34(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:40: T__35
    	    {
    	        /* 1:40: T__35 */
    	        mT__35(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:46: T__36
    	    {
    	        /* 1:46: T__36 */
    	        mT__36(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:52: NeverUsedRule
    	    {
    	        /* 1:52: NeverUsedRule */
    	        mNeverUsedRule(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:66: FOR
    	    {
    	        /* 1:66: FOR */
    	        mFOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:70: INT_TYPE
    	    {
    	        /* 1:70: INT_TYPE */
    	        mINT_TYPE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:79: CHAR_TYPE
    	    {
    	        /* 1:79: CHAR_TYPE */
    	        mCHAR_TYPE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:89: VOID_TYPE
    	    {
    	        /* 1:89: VOID_TYPE */
    	        mVOID_TYPE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:99: ID
    	    {
    	        /* 1:99: ID */
    	        mID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:102: INT
    	    {
    	        /* 1:102: INT */
    	        mINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:106: EQ
    	    {
    	        /* 1:106: EQ */
    	        mEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:109: EQEQ
    	    {
    	        /* 1:109: EQEQ */
    	        mEQEQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:114: OPLT
    	    {
    	        /* 1:114: OPLT */
    	        mOPLT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:119: PLUS
    	    {
    	        /* 1:119: PLUS */
    	        mPLUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // C:\\Users\\Alon\\Documents\\GitHub\\modern\\compiler\\ModernCompiler\\Modern.g:1:124: WS
    	    {
    	        /* 1:124: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
